const { Router } = require('express');
const { authenticateToken, requireRole } = require('../../../core/middleware');
const homeAdminController = require('../../controllers/admin/homeAdminController');

const router = Router();
const adminAuth = [authenticateToken, requireRole('admin', 'super_admin')];

router.get('/categories', adminAuth, homeAdminController.listCategories);
router.post('/categories', adminAuth, homeAdminController.createCategory);
router.put('/categories/:id', adminAuth, homeAdminController.updateCategory);
router.delete('/categories/:id', adminAuth, homeAdminController.deleteCategory);
router.get('/banners', adminAuth, homeAdminController.listBanners);
router.post('/banners', adminAuth, homeAdminController.createBanner);
router.put('/banners/:id', adminAuth, homeAdminController.updateBanner);
router.delete('/banners/:id', adminAuth, homeAdminController.deleteBanner);
router.get('/config', adminAuth, homeAdminController.getHomeConfig);
router.get('/config/list', adminAuth, homeAdminController.listHomeConfigs);
router.post('/config', adminAuth, homeAdminController.upsertHomeConfig);
router.put('/config', adminAuth, homeAdminController.updateHomeConfig);
router.delete('/config', adminAuth, homeAdminController.deleteHomeConfig);
router.get('/section-definitions', adminAuth, homeAdminController.listSectionDefinitions);
router.post('/section-definitions', adminAuth, homeAdminController.createSectionDefinition);
router.put('/section-definitions/:id', adminAuth, homeAdminController.updateSectionDefinition);
router.delete('/section-definitions/:id', adminAuth, homeAdminController.deleteSectionDefinition);
router.get('/sections', adminAuth, homeAdminController.listHomeSections);
router.post('/sections', adminAuth, homeAdminController.createHomeSection);
router.put('/sections/:id', adminAuth, homeAdminController.updateHomeSection);
router.delete('/sections/:id', adminAuth, homeAdminController.deleteHomeSection);
router.get('/lifestyle', adminAuth, homeAdminController.listLifestyle);
router.post('/lifestyle', adminAuth, homeAdminController.createLifestyle);
router.put('/lifestyle/:id', adminAuth, homeAdminController.updateLifestyle);
router.delete('/lifestyle/:id', adminAuth, homeAdminController.deleteLifestyle);
router.get('/promoblocks', adminAuth, homeAdminController.listPromoBlocks);
router.post('/promoblocks', adminAuth, homeAdminController.createPromoBlock);
router.put('/promoblocks/:id', adminAuth, homeAdminController.updatePromoBlock);
router.delete('/promoblocks/:id', adminAuth, homeAdminController.deletePromoBlock);
router.post('/upload-product-image', adminAuth, homeAdminController.uploadProductImage);
router.get('/products', adminAuth, homeAdminController.listProducts);
router.post('/products', adminAuth, homeAdminController.createProduct);
router.patch('/products/bulk', adminAuth, homeAdminController.bulkUpdateProducts);
router.put('/products/:id', adminAuth, homeAdminController.updateProduct);
router.delete('/products/:id', adminAuth, homeAdminController.deleteProduct);
router.get('/attributes', adminAuth, homeAdminController.listAttributes);
router.post('/attributes', adminAuth, homeAdminController.createAttribute);
router.put('/attributes/:id', adminAuth, homeAdminController.updateAttribute);
router.delete('/attributes/:id', adminAuth, homeAdminController.deleteAttribute);
module.exports = router;
